In [1]:
# HANDS ON SESSION BY INTELLIPAAT.

# **DATA SET UPLOADING:-**

In [2]:
from google.colab import files
uploaded = files.upload()

Saving census-income_.csv to census-income_.csv


# **Importing Required Libraries:-**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# **Data Reading:-**

In [4]:
df=pd.read_csv('census-income_.csv')
df.head(10)

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   
5   37            Private   284582     Masters              14   
6   49            Private   160187         9th               5   
7   52   Self-emp-not-inc   209642     HS-grad               9   
8   31            Private    45781     Masters              14   
9   42            Private   159449   Bachelors              13   

           marital-status          occupation    relationship    race  \
0           Never-married        Adm-clerical   Not-in-family   White   
1      Married-civ-spouse     Exec-managerial         Husband   White   
2                Divorced   Handlers-cleaners   Not-in-family   White   
3      Married-civ-spouse   Handlers-cleaners         Husband   Black   
4      Married-civ-spouse      Prof-specialty            Wife   Black   
5      Married-civ-spouse     Exec-managerial            Wife   White   
6   Married-spouse-absent       Other-service   Not-in-family   Black   
7      Married-civ-spouse     Exec-managerial         Husband   White   
8           Never-married      Prof-specialty   Not-in-family   White   
9      Married-civ-spouse     Exec-managerial         Husband   White   

       sex   capital-gain   capital-loss   hours-per-week  native-country  \
0     Male           2174              0               40   United-States   
1     Male              0              0               13   United-States   
2     Male              0              0               40   United-States   
3     Male              0              0               40   United-States   
4   Female              0              0               40            Cuba   
5   Female              0              0               40   United-States   
6   Female              0              0               16         Jamaica   
7     Male              0              0               45   United-States   
8   Female          14084              0               50   United-States   
9     Male           5178              0               40   United-States   

  annual Income  
0         <=50K  
1         <=50K  
2         <=50K  
3         <=50K  
4         <=50K  
5         <=50K  
6         <=50K  
7          >50K  
8          >50K  
9          >50K

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              32561 non-null  int64 
 1    workclass       32561 non-null  object
 2    fnlwgt          32561 non-null  int64 
 3    education       32561 non-null  object
 4    education-num   32561 non-null  int64 
 5    marital-status  32561 non-null  object
 6    occupation      32561 non-null  object
 7    relationship    32561 non-null  object
 8    race            32561 non-null  object
 9    sex             32561 non-null  object
 10   capital-gain    32561 non-null  int64 
 11   capital-loss    32561 non-null  int64 
 12   hours-per-week  32561 non-null  int64 
 13   native-country  32561 non-null  object
 14  annual Income    32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


# **EDA Process:-**

In [6]:
df.isnull().sum() # checking for duplicate values

age                0
 workclass         0
 fnlwgt            0
 education         0
 education-num     0
 marital-status    0
 occupation        0
 relationship      0
 race              0
 sex               0
 capital-gain      0
 capital-loss      0
 hours-per-week    0
 native-country    0
annual Income      0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(24)

In [8]:
# Eliminating duplicated values:-
df.drop_duplicates(inplace=True)

# **Label Encoding:-**

In [16]:
obj_columns=df.select_dtypes(include='object').columns
obj_columns

Index([' marital-status', ' occupation', ' relationship', ' race', ' sex',
       ' native-country', 'annual Income'],
      dtype='object')

In [10]:
df[' education'].value_counts()

education
HS-grad         10494
Some-college     7282
Bachelors        5353
Masters          1722
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           645
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           332
1st-4th           166
Preschool          50
Name: count, dtype: int64

# education Column is not that much important.

In [11]:
df.drop(columns=' education',inplace=True)

In [12]:
df['age'].value_counts()

age
36    898
31    888
34    886
23    876
35    875
     ... 
83      6
88      3
85      3
86      1
87      1
Name: count, Length: 73, dtype: int64

# 'age' column is not that much important

In [13]:
df.drop(columns='age',inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32537 entries, 0 to 32560
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0    workclass       32537 non-null  object
 1    fnlwgt          32537 non-null  int64 
 2    education-num   32537 non-null  int64 
 3    marital-status  32537 non-null  object
 4    occupation      32537 non-null  object
 5    relationship    32537 non-null  object
 6    race            32537 non-null  object
 7    sex             32537 non-null  object
 8    capital-gain    32537 non-null  int64 
 9    capital-loss    32537 non-null  int64 
 10   hours-per-week  32537 non-null  int64 
 11   native-country  32537 non-null  object
 12  annual Income    32537 non-null  object
dtypes: int64(5), object(8)
memory usage: 3.5+ MB


In [17]:
le=LabelEncoder()
for col in obj_columns:

  df[col]=le.fit_transform(df[col])

In [18]:
sc=StandardScaler()
df[' fnlwgt']=sc.fit_transform(df[[' fnlwgt']])
df[' capital-gain']=sc.fit_transform(df[[' capital-gain']])


In [19]:
df

workclass    fnlwgt   education-num   marital-status   occupation  \
0               7 -1.063569              13                4            1   
1               6 -1.008668              13                2            4   
2               4  0.245040               9                0            6   
3               4  0.425752               7                2            6   
4               4  1.408066              13                2           10   
...           ...       ...             ...              ...          ...   
32556           4  0.639678              12                2           13   
32557           4 -0.335436               9                2            7   
32558           4 -0.358779               9                6            1   
32559           4  0.110930               9                4            1   
32560           5  0.929812               9                2            4   

        relationship   race   sex   capital-gain   capital-loss  \
0                  1      4     1       0.148292              0   
1                  0      4     1      -0.145975              0   
2                  1      4     1      -0.145975              0   
3                  0      2     1      -0.145975              0   
4                  5      2     0      -0.145975              0   
...              ...    ...   ...            ...            ...   
32556              5      4     0      -0.145975              0   
32557              0      4     1      -0.145975              0   
32558              4      4     0      -0.145975              0   
32559              3      4     1      -0.145975              0   
32560              5      4     0       1.887635              0   

        hours-per-week   native-country  annual Income  
0                   40               39              0  
1                   13               39              0  
2                   40               39              0  
3                   40               39              0  
4                   40                5              0  
...                ...              ...            ...  
32556               38               39              0  
32557               40               39              1  
32558               40               39              0  
32559               20               39              0  
32560               40               39              1  

[32537 rows x 13 columns]

# **ML PROCESSES:-**

In [20]:
x=df.drop(columns='annual Income')

In [21]:
y=df['annual Income']

In [22]:
y.value_counts() #imbalance data

annual Income
0    24698
1     7839
Name: count, dtype: int64

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=42)

## **LDA PROCESS:-**

In [24]:
lda=LinearDiscriminantAnalysis()
lda.fit(x_train,y_train)

LinearDiscriminantAnalysis()

In [25]:
lda.transform(x_test)

array([[ 0.3424494 ],
       [ 1.33015104],
       [-0.05754559],
       ...,
       [ 1.40491162],
       [-0.63234788],
       [-0.49584634]])

In [26]:
lda.coef_

array([[-0.03418343,  0.02788454,  0.32553933, -0.23813602,  0.01372567,
        -0.19911465,  0.10438649,  0.67207694,  0.52288688,  0.0008771 ,
         0.02436851, -0.00171441]])

In [27]:
strength=np.abs(lda.coef_)

In [28]:
strength

array([[0.03418343, 0.02788454, 0.32553933, 0.23813602, 0.01372567,
        0.19911465, 0.10438649, 0.67207694, 0.52288688, 0.0008771 ,
        0.02436851, 0.00171441]])

In [29]:
value=strength.flatten()

In [30]:
value

array([0.03418343, 0.02788454, 0.32553933, 0.23813602, 0.01372567,
       0.19911465, 0.10438649, 0.67207694, 0.52288688, 0.0008771 ,
       0.02436851, 0.00171441])

In [31]:
new_df=pd.DataFrame({'columns':x_train.columns,'strength':value})

In [32]:
new_df

columns  strength
0         workclass  0.034183
1            fnlwgt  0.027885
2     education-num  0.325539
3    marital-status  0.238136
4        occupation  0.013726
5      relationship  0.199115
6              race  0.104386
7               sex  0.672077
8      capital-gain  0.522887
9      capital-loss  0.000877
10   hours-per-week  0.024369
11   native-country  0.001714

In [33]:
best_col1=new_df.nlargest(5,'strength')['columns']

In [34]:
best_col1

7                sex
8       capital-gain
2      education-num
3     marital-status
5       relationship
Name: columns, dtype: object

In [35]:
best_col2=new_df.nlargest(8,'strength')['columns']

In [36]:
best_col2

7                sex
8       capital-gain
2      education-num
3     marital-status
5       relationship
6               race
0          workclass
1             fnlwgt
Name: columns, dtype: object

## **MODEL PREDECTION:-**

In [37]:
x_train1=x_train.iloc[:,best_col1.index]
x_test1=x_test.iloc[:,best_col1.index]

In [38]:
x_train2=x_train.iloc[:,best_col2.index]
x_test2=x_test.iloc[:,best_col2.index]

# Classification Models:-

In [39]:
model1=LogisticRegression()
model2=DecisionTreeClassifier()
model3=RandomForestClassifier()

# Logistic Regression:-

In [40]:
model1.fit(x_train1,y_train)
print('Accuracy Score:',roc_auc_score(y_test,model1.predict(x_test1)))

Accuracy Score: 0.7189020800627944


In [41]:
model1.fit(x_train2,y_train)
print('Accuracy Score:',roc_auc_score(y_test,model1.predict(x_test2)))

Accuracy Score: 0.7131873295877055


# Decision Tree Classifier:-

In [42]:
model2.fit(x_train1,y_train)
print('Accuracy Score:',roc_auc_score(y_test,model2.predict(x_test1)))

Accuracy Score: 0.7465421796248864


In [43]:
model2.fit(x_train2,y_train)
print('Accuracy Score:',roc_auc_score(y_test,model2.predict(x_test2)))

Accuracy Score: 0.725007229612493


# Ramdom Forest Classifier:-

In [44]:
model3.fit(x_train1,y_train)
print('Accuracy Score:',roc_auc_score(y_test,model3.predict(x_test1)))

Accuracy Score: 0.7480201189787656


In [45]:
model3.fit(x_train2,y_train)
print('Accuracy Score:',roc_auc_score(y_test,model3.predict(x_test2)))

Accuracy Score: 0.7269390853507395


# Random Forest Classifier Fits Best